### ISSUE TITLE
New unlocker?

### ISSUE THREAD

**Issue by peske** [DrDonk/darwin#1]
Hey @DrDonk 
I was very surprised that your `unlocker` repo is removed! Legal issues or something? Please continue your work on this! I'm willing to support with some donation - pls provide details...
Thanks!

**Comment by DrDonk** [comment]
I lost interest in the project after working on it for many many years. I also now use my Github account for my professional work and I decided that I needed to remove the repos as they exist in a grey area.

Please note Apple and VMware have never asked me to take down the code. Apple has only ever gone after anyone trying to make money off Hackintoshes.
